CREATE TABLE IF NOT EXISTS "migrations" ("id" integer primary key autoincrement not null, "migration" varchar not null, "batch" integer not null);
CREATE TABLE IF NOT EXISTS "users" ("id" integer primary key autoincrement not null, "name" varchar not null, "email" varchar not null, "email_verified_at" datetime, "password" varchar not null, "remember_token" varchar, "created_at" datetime, "updated_at" datetime);
CREATE UNIQUE INDEX "users_email_unique" on "users" ("email");
CREATE TABLE IF NOT EXISTS "password_reset_tokens" ("email" varchar not null, "token" varchar not null, "created_at" datetime, primary key ("email"));
CREATE TABLE IF NOT EXISTS "failed_jobs" ("id" integer primary key autoincrement not null, "uuid" varchar not null, "connection" text not null, "queue" text not null, "payload" text not null, "exception" text not null, "failed_at" datetime not null default CURRENT_TIMESTAMP);
CREATE UNIQUE INDEX "failed_jobs_uuid_unique" on "failed_jobs" ("uuid");
CREATE TABLE IF NOT EXISTS "personal_access_tokens" ("id" integer primary key autoincrement not null, "tokenable_type" varchar not null, "tokenable_id" integer not null, "name" varchar not null, "token" varchar not null, "abilities" text, "last_used_at" datetime, "expires_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE INDEX "personal_access_tokens_tokenable_type_tokenable_id_index" on "personal_access_tokens" ("tokenable_type", "tokenable_id");
CREATE UNIQUE INDEX "personal_access_tokens_token_unique" on "personal_access_tokens" ("token");
CREATE TABLE IF NOT EXISTS "receitas" ("id" integer primary key autoincrement not null, "user_id" integer not null, "saldo" varchar not null, "custo" varchar not null default '0', "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "status_dispesas" ("id" integer primary key autoincrement not null, "nome" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "dispesas" ("id" integer primary key autoincrement not null, "descricao" varchar not null, "data_vencimento" varchar not null, "status_dispesa_id" integer not null, "tipo_dispesa_id" integer not null, "plano_id" integer not null, "valor_documento" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "tipo_dispesas" ("id" integer primary key autoincrement not null, "nome" varchar not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "imports" ("id" integer primary key autoincrement not null, "completed_at" datetime, "file_name" varchar not null, "file_path" varchar not null, "importer" varchar not null, "processed_rows" integer not null default '0', "total_rows" integer not null, "successful_rows" integer not null default '0', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "exports" ("id" integer primary key autoincrement not null, "completed_at" datetime, "file_disk" varchar not null, "file_name" varchar, "exporter" varchar not null, "processed_rows" integer not null default '0', "total_rows" integer not null, "successful_rows" integer not null default '0', "user_id" integer not null, "created_at" datetime, "updated_at" datetime, foreign key("user_id") references "users"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "failed_import_rows" ("id" integer primary key autoincrement not null, "data" text not null, "import_id" integer not null, "validation_error" text, "created_at" datetime, "updated_at" datetime, foreign key("import_id") references "imports"("id") on delete cascade);
CREATE TABLE IF NOT EXISTS "planos" ("id" integer primary key autoincrement not null, "descricao_simples" varchar not null, "mes_ano" varchar not null, "user_id" integer not null, "deleted_at" datetime, "created_at" datetime, "updated_at" datetime);
CREATE TABLE IF NOT EXISTS "gastos" ("id" integer primary key autoincrement not null, "plano_id" integer not null, "valor" varchar not null, "created_at" datetime, "updated_at" datetime);
INSERT INTO migrations VALUES(1,'2014_10_12_000000_create_users_table',1);
INSERT INTO migrations VALUES(2,'2014_10_12_100000_create_password_reset_tokens_table',1);
INSERT INTO migrations VALUES(3,'2019_08_19_000000_create_failed_jobs_table',1);
INSERT INTO migrations VALUES(4,'2019_12_14_000001_create_personal_access_tokens_table',1);
INSERT INTO migrations VALUES(5,'2024_03_20_065530_create_receitas_table',1);
INSERT INTO migrations VALUES(6,'2024_03_20_065555_create_status_dispesas_table',1);
INSERT INTO migrations VALUES(7,'2024_03_20_070410_create_dispesas_table',1);
INSERT INTO migrations VALUES(8,'2024_03_20_070648_create_tipo_dispesas_table',1);
INSERT INTO migrations VALUES(9,'2024_03_20_074745_create_imports_table',1);
INSERT INTO migrations VALUES(10,'2024_03_20_074746_create_exports_table',1);
INSERT INTO migrations VALUES(11,'2024_03_20_074747_create_failed_import_rows_table',1);
INSERT INTO migrations VALUES(12,'2024_03_20_223754_create_planos_table',1);
INSERT INTO migrations VALUES(13,'2024_03_25_224257_create_gastos_table',2);
