name: test

on:
  push:
    branches: [ "release", "test" ]
  pull_request:
    branches: [ "release", "test" ]

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: [8.4]

  docker-build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Docker Login
        uses: docker/login-action@v3.2.0
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Construção da imagem Docker
        uses: docker/build-push-action@v6
        with:
          file: ./docker/8.3/Dockerfile
          push: true
          tags: |
              phantasmablack/meu-financeiro:${{github.run_number}}
              phantasmablack/meu-financeiro:latest
