name: test

on:
  push:
    branches: [ "release", "test" ]
  pull_request:
    branches: [ "release", "test" ]

jobs:
  tests-automatizado:

    runs-on: ubuntu-latest

    steps:
    - uses: shivammathur/setup-php@15c43e89cdef867065b0213be354c2841860869e
      with:
        php-version: '8.3'
    - uses: actions/checkout@v4
    - name: Copy .env
      run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    - name: Install Dependencies
      run: composer install -q --no-ansi --no-interaction --no-scripts --no-progress --prefer-dist
    - name: Generate key
      run: php artisan key:generate
    - name: Directory Permissions
      run: chmod -R 777 storage bootstrap/cache
    - name: Create Database
      run: |
        mkdir -p database
        touch database/database.sqlite
    - name: Execute tests (Unit and Feature tests) via PHPUnit/Pest
      env:
        DB_CONNECTION: sqlite
        DB_DATABASE: database/database.sqlite
      run: |
        php artisan test
  # docker-build:
  #   runs-on: ubuntu-latest
  #   needs: laravel-tests
  #   steps:
  #     - name: Checkout
  #       uses: actions/checkout@v4
  #     - name: Set up QEMU
  #       uses: docker/setup-qemu-action@v3
  #     - name: Set up Docker Buildx
  #       uses: docker/setup-buildx-action@v3
  #     - name: Docker Login
  #       uses:  docker/login-action@v3.2.0
  #       with:
  #         username: ${{secrets.DOCKER_USER}}
  #         password: ${{secrets.DOCKER_PASS}}

  #     - name: Construção da imagem Docker
  #       uses: docker/build-push-action@v6
  #       with:
  #         file: ./docker/8.3/Dockerfile
  #         push: true
  #         tags: |
  #           phantasmablack/meu-financeiro:${{github.run_number}}
  #           phantasmablack/meu-financeiro:latest
